# Generated by Django 5.0.1 on 2026-01-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_private_keys',
            field=models.TextField(blank=True, help_text='Backup chiffré des clés privées {dh_private, sign_private} en JSON', null=True),
        ),
    ]
