# Generated by Django 5.0.1 on 2026-01-18 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group')], db_index=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messagerie.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('VOICE', 'Voice'), ('FILE', 'File'), ('SYSTEM', 'System')], default='TEXT', max_length=20)),
                ('encrypted_content', models.TextField(help_text='Ciphertext AES-256-GCM (Base64)')),
                ('nonce', models.CharField(default='', help_text='Nonce AES-GCM (Base64) - 12 bytes', max_length=255)),
                ('auth_tag', models.CharField(default='', help_text='Authentication tag AES-GCM (Base64) - 16 bytes', max_length=255)),
                ('signature', models.TextField(default='', help_text='Signature Ed25519 du hash du ciphertext (Base64)')),
                ('metadata', models.JSONField(blank=True, help_text='Métadonnées non sensibles (file_name, size, etc.)', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversation')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messagerie.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('VOICE', 'Voice Note'), ('FILE', 'File')], db_index=True, max_length=20)),
                ('encrypted_file_url', models.TextField(help_text='URL to encrypted file blob')),
                ('encrypted_thumbnail_url', models.TextField(blank=True, default='', help_text='URL to encrypted thumbnail')),
                ('encrypted_filename', models.TextField(blank=True, default='', help_text='Original filename (encrypted)')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds (audio/video only)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(blank=True, help_text='Width in pixels', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(blank=True, help_text='Height in pixels', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('encrypted_metadata', models.TextField(blank=True, default='', help_text='Additional encrypted metadata')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('upload_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='messagerie.message')),
            ],
            options={
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read')], db_index=True, default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Quand le message a été envoyé')),
                ('delivered_at', models.DateTimeField(blank=True, help_text="Quand l'utilisateur a reçu le message", null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text="Quand l'utilisateur a lu le message", null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='messagerie.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Status',
                'verbose_name_plural': 'Message Statuses',
                'db_table': 'message_statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default='', help_text='Custom nickname for this contact', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Private notes about this contact')),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-is_favorite', '-added_at'],
                'indexes': [models.Index(fields=['user', 'is_blocked'], name='contacts_user_id_0ee143_idx'), models.Index(fields=['user', 'is_favorite'], name='contacts_user_id_80e197_idx'), models.Index(fields=['user', 'added_at'], name='contacts_user_id_7122a0_idx')],
                'unique_together': {('user', 'contact_user')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type'], name='messagerie__type_5d7b24_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='messagerie__last_me_833655_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user'], name='messagerie__user_id_7975a3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation'], name='messagerie__convers_b41361_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_user'], name='messages_from_us_0cd2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['message', 'type'], name='media_message_5b68e8_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['type', 'created_at'], name='media_type_1d82fb_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['is_uploaded'], name='media_is_uplo_55ed36_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='message_sta_user_id_a702ec_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'status'], name='message_sta_message_2b01cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
    ]
