# Generated by Django 5.0.1 on 2026-01-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, help_text='Dernier message envoyé dans cette conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_last_message', to='messagerie.message'),
        ),
    ]
